# Generated by Django 3.2.10 on 2021-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='class_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
